#!/bin/sh -e

case $1 in
    purge)
        systemctl disable bubbleupnp
        systemctl daemon-reload

        rm -rf /var/opt/bubbleupnp

        echo "Removing \`bubbleupnp' user ..."
        userdel -r bubbleupnp > /dev/null 2>&1

        ;;
    remove)
		rm /usr/lib/arm-linux-gnueabihf/libx264.so.152
		rm /usr/lib/arm-linux-gnueabihf/libx265.so.146
        systemctl daemon-reload
        ;;
    upgrade)
        ;;
    *)
        ;;
esac
